apiVersion: core.paladin.io/v1alpha1
kind: SmartContractDeployment
metadata:
  
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator-go
  name: zeto-g16-check-hashes-value
spec:
  abiJSON: |-
    [
      {
        "inputs": [
          {
            "internalType": "uint256[2]",
            "name": "_pA",
            "type": "uint256[2]"
          },
          {
            "internalType": "uint256[2][2]",
            "name": "_pB",
            "type": "uint256[2][2]"
          },
          {
            "internalType": "uint256[2]",
            "name": "_pC",
            "type": "uint256[2]"
          },
          {
            "internalType": "uint256[2]",
            "name": "_pubSignals",
            "type": "uint256[2]"
          }
        ],
        "name": "verifyProof",
        "outputs": [
          {
            "internalType": "bool",
            "name": "",
            "type": "bool"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      }
    ]
  bytecode: 0x6080604052348015600f57600080fd5b5061063b8061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063f5c9d69e14610030575b600080fd5b61004a60048036038101906100459190610566565b610060565b60405161005791906105ea565b60405180910390f35b60006104dc565b7f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f00000018110610098576000805260206000f35b50565b600060405183815284602082015285604082015260408160608360076107d05a03fa9150816100ce576000805260206000f35b825160408201526020830151606082015260408360808360066107d05a03fa9150816100fe576000805260206000f35b505050505050565b600060808601600087017f0c24983138eee0db0ec113bb8abc3010600b70c710b572f6e656acebe38874c481527ee6496758069ae75ab5842ba40e67e3f8f87f837272397842739abae350d8a660208201526101a860008801357f1e087a4acb54d6e8f9050fc6775e03bfe48d50f4763c1fdf96d0f7cdb77c30bf7f11c4233295814bf04c3c2c5e31d01f664d56cfe58c48660501cd143a6d6335708461009b565b6101f860208801357f2349d935afdffe08b9aa3ce71e9ccc8ae440c45b06ea0d31b40c30635ddc7c8d7f14ba9f76b09885cfe773cba1eae07bf6879835f069af1b383a8ad8c5bb2bf48e8461009b565b833582527f30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd4760208501357f30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd4703066020830152843560408301526020850135606083015260408501356080830152606085013560a08301527f2d4d9aa7e302d9df41749d5507949d05dbea33fbb16c643b22f599a2be6df2e260c08301527f14bedd503c37ceb061d8ec60209fe345ce89830a19230301f076caff004d192660e08301527f0967032fcbf776d1afc985f88877f182d38480a653f2decaa9794cbc3bf3060c6101008301527f0e187847ad4c798374d0d6732bf501847dd68bc0e071241e0213bc7fc13db7ab6101208301527f304cfbd1e08a704a99f5e847d93f8c3caafddec46b7a0d379da69a4d112346a76101408301527f1739c1b1a457a8c7313123d24d2f9192f896b7c63eea05a9d57f06547ad0cec8610160830152600088015161018083015260206000018801516101a08301527f198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c26101c08301527f1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed6101e08301527f090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b6102008301527f12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa610220830152853561024083015260208601356102608301527f198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c26102808301527f1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed6102a08301527f090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b6102c08301527f12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa6102e08301526020826103008460086107d05a03fa82518116935050505095945050505050565b60405161038081016040526104f46000840135610067565b6105016020840135610067565b61050e818486888a610106565b8060005260206000f35b600080fd5b600080fd5b60008190508260206002028201111561053e5761053d61051d565b5b92915050565b6000819050826040600202820111156105605761055f61051d565b5b92915050565b600080600080610140858703121561058157610580610518565b5b600061058f87828801610522565b94505060406105a087828801610544565b93505060c06105b187828801610522565b9250506101006105c387828801610522565b91505092959194509250565b60008115159050919050565b6105e4816105cf565b82525050565b60006020820190506105ff60008301846105db565b9291505056fea264697066735822122023411ad636e67b43ace4cdf3ed84efdb89161d0af62b19ab5a9a6d42fad4227564736f6c634300081b0033
  from: zeto.operator
  node: node1
  paramsJSON: '{}'
  txType: public
status: {}
