apiVersion: core.paladin.io/v1alpha1
kind: SmartContractDeployment
metadata:
  
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator-go
  name: zeto-g16-verifier-anon-nullifier
spec:
  abiJSON: |-
    [
      {
        "inputs": [
          {
            "internalType": "uint256[2]",
            "name": "_pA",
            "type": "uint256[2]"
          },
          {
            "internalType": "uint256[2][2]",
            "name": "_pB",
            "type": "uint256[2][2]"
          },
          {
            "internalType": "uint256[2]",
            "name": "_pC",
            "type": "uint256[2]"
          },
          {
            "internalType": "uint256[7]",
            "name": "_pubSignals",
            "type": "uint256[7]"
          }
        ],
        "name": "verifyProof",
        "outputs": [
          {
            "internalType": "bool",
            "name": "",
            "type": "bool"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      }
    ]
  bytecode: 0x6080604052348015600f57600080fd5b5061082f8061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063c894e75714610030575b600080fd5b61004a6004803603810190610045919061075a565b610060565b60405161005791906107de565b60405180910390f35b600061066d565b7f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f00000018110610098576000805260206000f35b50565b600060405183815284602082015285604082015260408160608360076107d05a03fa9150816100ce576000805260206000f35b825160408201526020830151606082015260408360808360066107d05a03fa9150816100fe576000805260206000f35b505050505050565b600060808601600087017f23e261ff6227d7ced5de8c0cbdd69f97ee73b8aa5950ee95ea7b686957f6589381527f1587eddadf33489d360b501c4f6d23f51e1dc283a5d6617e74ad4676b0bcfb0b60208201526101a960008801357f30090055e59bc613858a4b4092ecb6fe365ee78299bb348b1550874d9d355fee7f0292b62411021303475adbc56e311846a3f0df000a3090b72b72572042e4a3148461009b565b6101f960208801357f2ef6ffb1cf7e5dc1328bb1ff10f6dab3d6a5d6fa65d01b57bdc33f369faa0dec7f02b5c47baf15fbcdc096563e8fa133a547116dff8cbbefbf3e57db7f45cd61d08461009b565b61024960408801357f1789f6480b2c0e5b41cc269b412553f5708349c28e36cb7ec94a4fafcd1396b77f120b8f71622cf2e6a8ab0fe510d570b9d4d7546e24a3ea5e2ec6c48526847db58461009b565b61029960608801357f2bf13168b64f9444372ff2ad2e13fea2dc30e54320e43e6c9d6e39ab59e71f0d7f2646c00178064f64b9ce27c0f1b3426592a03c692ff56a27f6319e8698b438228461009b565b6102e960808801357f1a745db17f69eb8bc5df51e11153e0e34a263c089e927249d0c426468b8317ac7f199b15c2922dd6f350d29404a850216155e09b11db6628d8808d416118fe48738461009b565b61033960a08801357f0a370ba45b5d20eab92a6379f953ae4b60c200f029b268459c6f977b57dfa09e7f228b729130c41748eb5d6385b889b3dbfdbb13a8795aee64316f3cb4b3ce86198461009b565b61038960c08801357f169b22d88ffb6421c6ddd9a2aee011e3d0f03d0e87b71b1650f639d78c57b91a7f2b960b033439b1d29a338c059b4995b5f03ba1b409c2f4cf72e76e4c0c0ea9de8461009b565b833582527f30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd4760208501357f30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd4703066020830152843560408301526020850135606083015260408501356080830152606085013560a08301527f2d4d9aa7e302d9df41749d5507949d05dbea33fbb16c643b22f599a2be6df2e260c08301527f14bedd503c37ceb061d8ec60209fe345ce89830a19230301f076caff004d192660e08301527f0967032fcbf776d1afc985f88877f182d38480a653f2decaa9794cbc3bf3060c6101008301527f0e187847ad4c798374d0d6732bf501847dd68bc0e071241e0213bc7fc13db7ab6101208301527f304cfbd1e08a704a99f5e847d93f8c3caafddec46b7a0d379da69a4d112346a76101408301527f1739c1b1a457a8c7313123d24d2f9192f896b7c63eea05a9d57f06547ad0cec8610160830152600088015161018083015260206000018801516101a08301527f198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c26101c08301527f1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed6101e08301527f090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b6102008301527f12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa610220830152853561024083015260208601356102608301527f198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c26102808301527f1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed6102a08301527f090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b6102c08301527f12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa6102e08301526020826103008460086107d05a03fa82518116935050505095945050505050565b60405161038081016040526106856000840135610067565b6106926020840135610067565b61069f6040840135610067565b6106ac6060840135610067565b6106b96080840135610067565b6106c660a0840135610067565b6106d360c0840135610067565b6106e0818486888a610106565b8060005260206000f35b600080fd5b600080fd5b6000819050826020600202820111156107105761070f6106ef565b5b92915050565b600081905082604060020282011115610732576107316106ef565b5b92915050565b600081905082602060070282011115610754576107536106ef565b5b92915050565b6000806000806101e08587031215610775576107746106ea565b5b6000610783878288016106f4565b945050604061079487828801610716565b93505060c06107a5878288016106f4565b9250506101006107b787828801610738565b91505092959194509250565b60008115159050919050565b6107d8816107c3565b82525050565b60006020820190506107f360008301846107cf565b9291505056fea264697066735822122029f722439dba206ce8bdb2cbcdb0a4814798e8bcf010affe9e7700297f3400c864736f6c634300081b0033
  from: zeto.operator
  node: node1
  paramsJSON: '{}'
  txType: public
status: {}
